version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: customerDB
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: CRM
      MYSQL_USER: sherry
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: